### ISSUE TITLE
Implement the actual list for the Calendar Overview

### ISSUE THREAD

**Issue by grittaweisheit** [MichaelBuessemeyer/MyTrainingsPal#30] opened 2022-12-28 21:18 UTC
![image](https://user-images.githubusercontent.com/44833037/209873147-4392c4cd-54c5-4743-859c-7d3bb60bd751.png)

**Comment by MichaelBuessemeyer** [comment] 2022-12-30 19:16
Duplicate of #10

**Closed by MichaelBuessemeyer** 2022-12-30 19:16 UTC
